RDPMBT-708 - Upgrade React
OutSystems/ReactView pull request #75
Opened 2022-03-11 18:24 UTC by heldergoncalves92

2022-03-11 18:46 UTC, joaompneves commented on ReactViewResources/package-lock.json
> +  "lockfileVersion": 1,
upgrade your node/npm

2022-03-14 16:04 UTC, joaompneves requested changes

2022-03-14 16:04 UTC, joaompneves commented on Directory.Build.props
> +    <Version>2.92.0</Version>
91 -> is the version of the webview used .. so dont raise that number

2022-03-14 16:44 UTC, joaompneves requested changes

2022-03-14 17:04 UTC, heldergoncalves92 commented on Sample.Avalonia/MainView/MainView.tsx
> +                <ComponentTest />
At the moment, I'm only testing the build and the runtime.
After everything is fine, I'll revert this.

Currently there are some issues on loading the `react/jsx-runtime`

2022-03-14 17:13 UTC, joaompneves commented on Directory.Build.props
> +    <Version>2.92.0</Version>
nope

2022-03-15 09:43 UTC, joaompneves commented on ViewGenerator/tools/package.json
> +        "typescript": "^4.2.2"
new dep?

2022-03-15 09:44 UTC, mpm-os commented on ViewGenerator/tools/package.json
> +        "typescript": "^4.2.2"
i believe this is not needed here..

2024-06-06 13:48 UTC, closed without merging